#import "SnapshotHelper.js"

var target = UIATarget.localTarget();
var app = target.frontMostApp();
var window = app.mainWindow();
target.setDeviceOrientation(UIA_DEVICE_ORIENTATION_LANDSCAPELEFT);

target.delay(5)
captureLocalizedScreenshot("0-LandingScreen")

target.frontMostApp().mainWindow().textViews()[0].tapWithOptions({tapOffset:{x:0.16, y:0.29}});
target.delay(5)
captureLocalizedScreenshot("1-LandingScreen")

target.frontMostApp().mainWindow().textViews()[0].tapWithOptions({tapOffset:{x:0.16, y:0.29}});
target.delay(5)
captureLocalizedScreenshot("2-LandingScreen")